import GuidedCameraView from "./components/GuidedCameraView";
export { GuidedCameraView };
export type { GuidedCameraViewProps, VideoData, SupportedLanguage, } from "./types";
export { PitchDetector } from "./utils/pitchDetector";
export { YawDetector } from "./utils/yawDetector";
export { MotionDetector } from "./utils/motionDetectorV2";
export { FallbackSpeedDetector as SpeedDetector } from "./utils/fallbackSpeedDetector";
export { RealtimeBrightnessDetector } from "./utils/realtimeBrightnessDetectorV2";
export type { AngleMetrics, PitchDetectorConfig } from "./utils/pitchDetector";
export type { YawMetrics, YawDetectorConfig } from "./utils/yawDetector";
export type { MotionMetrics, MotionDetectorConfig, } from "./utils/motionDetectorV2";
export type { SpeedMetrics, SpeedDetectorConfig, } from "./utils/fallbackSpeedDetector";
export type { LightingMetrics, RealtimeBrightnessConfig, } from "./utils/realtimeBrightnessDetectorV2";
export { calculateAngleColor, getAngleMessage } from "./utils/pitchDetector";
export { getYawColor, getYawMessage, shouldAllowRecordingYaw, } from "./utils/yawDetector";
export { getSpeedColor, getSpeedMessage, shouldAllowRecordingSpeed, getSpeedIcon, } from "./utils/fallbackSpeedDetector";
export { getTranslations, translations } from "./utils/translations";
export { useArabicFonts, getArabicTextStyle } from "./utils/fonts";
export { getAngleMessageTranslated } from "./utils/pitchDetector";
export { getYawMessageTranslated } from "./utils/yawDetector";
export { getMotionStabilityMessage } from "./utils/motionDetectorV2";
export { getSpeedRecommendationMessage, getSpeedMotionMessage, } from "./utils/fallbackSpeedDetector";
export { getBrightnessRecommendationMessage } from "./utils/realtimeBrightnessDetectorV2";
export default GuidedCameraView;
//# sourceMappingURL=index.d.ts.map